# Generated by Django 4.2.9 on 2024-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Телеграм_id'),
        ),
    ]
