# Generated by Django 5.0.1 on 2024-01-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('preview', models.ImageField(upload_to='course/lesson/', verbose_name='Превью урока')),
                ('link_to_video', models.URLField(verbose_name='Ссылка на видео')),
                ('from_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studies.course', verbose_name='ссылка на курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
