# Generated by Django 5.0.1 on 2024-01-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.CharField(max_length=256, verbose_name='Пользователь'),
        ),
    ]
