# Generated by Django 5.0.1 on 2024-01-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_alter_payments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_autor',
            new_name='lesson_author',
        ),
    ]
