# Generated by Django 5.0.1 on 2024-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_rename_lesson_autor_lesson_lesson_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Клиент'),
        ),
    ]
