# Generated by Django 5.0.1 on 2024-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Клиент'),
        ),
    ]
